"""initial_schema

Revision ID: 1bd2d99cf989
Revises:
Create Date: 2026-07-23 20:32:14.433234

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1bd2d99cf989"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("isbn", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("genre", sa.String(length=100), nullable=True),
        sa.Column("publisher", sa.String(length=255), nullable=True),
        sa.Column("publication_year", sa.SmallInteger(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("total_copies", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("available_copies", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column(
            "condition",
            sa.Enum("NEW", "GOOD", "FAIR", "POOR", name="bookcondition"),
            server_default="GOOD",
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "available_copies <= total_copies", name="chk_books_available_copies_lte_total"
        ),
        sa.CheckConstraint("available_copies >= 0", name="chk_books_available_copies_non_negative"),
        sa.CheckConstraint("total_copies >= 0", name="chk_books_total_copies_non_negative"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isbn"),
    )
    op.create_index("idx_books_author", "books", ["author"], unique=False)
    op.create_index("idx_books_genre", "books", ["genre"], unique=False)
    op.create_index("idx_books_isbn", "books", ["isbn"], unique=True)
    op.create_index("idx_books_title", "books", ["title"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "LIBRARIAN", "MEMBER", name="userrole"),
            server_default="MEMBER",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", name="userstatus"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("idx_users_email", "users", ["email"], unique=True)
    op.create_index("idx_users_role", "users", ["role"], unique=False)
    op.create_table(
        "members",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("membership_number", sa.String(length=50), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("joined_date", sa.Date(), nullable=False),
        sa.Column(
            "membership_status",
            sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", name="membershipstatus"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("membership_number"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index("idx_members_membership_num", "members", ["membership_number"], unique=True)
    op.create_index("idx_members_status", "members", ["membership_status"], unique=False)
    op.create_index("idx_members_user_id", "members", ["user_id"], unique=True)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "token_type",
            sa.Enum("REFRESH", name="tokentype"),
            server_default="REFRESH",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_refresh_token_hash", "refresh_tokens", ["token_hash"], unique=False)
    op.create_index("idx_refresh_user_id", "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "borrow_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("book_id", sa.String(length=36), nullable=False),
        sa.Column("borrow_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("return_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("renewal_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            sa.Enum("BORROWED", "RETURNED", "RENEWED", "OVERDUE", name="borrowstatus"),
            server_default="BORROWED",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("renewal_count <= 2", name="chk_borrow_renewal_count_max_limit"),
        sa.CheckConstraint("renewal_count >= 0", name="chk_borrow_renewal_count_non_negative"),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["member_id"], ["members.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_borrow_book_id", "borrow_records", ["book_id"], unique=False)
    op.create_index("idx_borrow_due_date", "borrow_records", ["due_date", "status"], unique=False)
    op.create_index("idx_borrow_member_id", "borrow_records", ["member_id"], unique=False)
    op.create_index("idx_borrow_status", "borrow_records", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_borrow_status", table_name="borrow_records")
    op.drop_index("idx_borrow_member_id", table_name="borrow_records")
    op.drop_index("idx_borrow_due_date", table_name="borrow_records")
    op.drop_index("idx_borrow_book_id", table_name="borrow_records")
    op.drop_table("borrow_records")
    op.drop_index("idx_refresh_user_id", table_name="refresh_tokens")
    op.drop_index("idx_refresh_token_hash", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("idx_members_user_id", table_name="members")
    op.drop_index("idx_members_status", table_name="members")
    op.drop_index("idx_members_membership_num", table_name="members")
    op.drop_table("members")
    op.drop_index("idx_users_role", table_name="users")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_books_title", table_name="books")
    op.drop_index("idx_books_isbn", table_name="books")
    op.drop_index("idx_books_genre", table_name="books")
    op.drop_index("idx_books_author", table_name="books")
    op.drop_table("books")
    # ### end Alembic commands ###
